In [1]:
%matplotlib inline
from visualizer import *
from outputs.rl_data import rl_output
import manager

In [2]:
def depth_dict_split(lst):
    '''
    Takes a lst of dictionary, return two list by depth.
    :param lst: 
    :return: 
    '''
    a = []
    b = []
    for i in lst:
        if i["depth"] == 1:
            a.append(i)
        else:
            b.append(i)
    return a, b

In [3]:
mcts50 = dict_txt_parser("outputs/results_mcts_single_count_(50,).txt")
mcts100 = dict_txt_parser("outputs/results_mcts_single_count_(100,).txt")
expectimax = dict_txt_parser("outputs/results_expectimax_single_count_(1, 2).txt")
minimax = dict_txt_parser("outputs/results_minimax_single_count_(1, 2).txt")
rl = rl_output
print("The length of data is {}".format(len(rl)))

The length of data is 20
The length of data is 20
The length of data is 200
The length of data is 200
The length of data is 35


In [4]:
expectimax1, expectimax2 = depth_dict_split(expectimax)
minimax1, minimax2 = depth_dict_split(minimax)

## 1. The comparison for minimax depth 1, 2, expectimax depth 1, 2

In [5]:
visual0 = Visualizer(x_range = np.arange(0,100))
visual0.add_data("minimax_depth1", minimax1)
visual0.add_data("minimax_depth2", minimax2)
visual0.add_data("expectimax_depth1", expectimax1)
visual0.add_data("expectimax_depth2", expectimax2)

visual0.draw_lines("movements")

In [6]:
visual0.draw_lines("score")

In [7]:
visual0.draw_grouped_bar("movements")

In [8]:
visual0.draw_stack_bar("max_tile")

[ 128  256  512 1024 2048] [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]
[ 256  512 1024 2048 4096] [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]
[ 128  256  512 1024] [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]
[ 128  256  512 1024 2048] [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]


## Comparison For MCTS

In [9]:
visual1 = Visualizer(x_range = np.arange(0,20))
visual1.add_data("mcts_depth50 ", mcts50)
visual1.add_data("mcts_depth100", mcts100)

visual1.draw_lines("movements")

In [11]:
visual1.draw_grouped_bar("score")

In [12]:
visual1.draw_stack_bar("max_tile")

[ 512 1024 2048] [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]
[ 512 1024 2048] [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]


## Comparison For ALL Algos.

In [13]:
visual2 = Visualizer(x_range = np.arange(0,20))
visual2.add_data("minimax_depth2", minimax2)
visual2.add_data("expectimax_depth2", expectimax2)
visual2.add_data("mcts_depth100", mcts100)
visual2.add_data("Reinforce Learning", rl)

visual2.draw_lines("movements")

In [14]:
visual2.draw_grouped_bar("score")

In [16]:
visual2.draw_stack_bar("max_tile")

[ 512 1024 2048 4096] [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]
[ 512 1024 2048] [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]
[ 64 128 256] [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]
[ 128  256  512 1024 2048] [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]
